apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000             #port that other object in the cluster can access that pod
      targetPort: 3000       #port of the target Pod